import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Auto-generated sidebar configuration for ELEVATE Design System
 * Each main area automatically detects and includes all files in its directory
 * No need to manually maintain file lists - just add/remove .md/.mdx files!
 * 
 * Benefits:
 * - Add new .md/.mdx files and they appear automatically
 * - Remove files and they disappear from navigation  
 * - No more crashes when files are missing
 * - Use sidebar_position in frontmatter to control order
 * - Use sidebar_label in frontmatter to customize labels
 */
const sidebars: SidebarsConfig = {
  // Home sidebar - Introduction and getting started
  homeSidebar: [
    {
      type: 'category',
      label: 'Home',
      link: {
        type: 'doc',
        id: 'home/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'home',
        },
      ],
    },
  ],

  // Guidelines sidebar - Design principles and best practices
  guidelinesSidebar: [
    {
      type: 'category',
      label: 'Guidelines',
      link: {
        type: 'doc',
        id: 'guidelines/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guidelines',
        },
      ],
    },
  ],

  // Components sidebar - All design system components with automatic detection
  componentsSidebar: [
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'doc',
        id: 'components/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'components',
        },
      ],
    },
  ],

  // Patterns sidebar - UI patterns and templates (auto-detected)
  patternsSidebar: [
    {
      type: 'category',
      label: 'Patterns',
      link: {
        type: 'doc',
        id: 'patterns/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'patterns',
        },
      ],
    },
  ],

  // Design sidebar - Design tokens and foundations (auto-detected)
  designSidebar: [
    {
      type: 'category',
      label: 'Design',
      link: {
        type: 'doc',
        id: 'design/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'design',
        },
      ],
    },
  ],

  // DS sidebar - Design System documentation meta (auto-detected)
  dsSidebar: [
    {
      type: 'category',
      label: 'DS',
      link: {
        type: 'doc',
        id: 'ds/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ds',
        },
      ],
    },
  ],
};

export default sidebars;