import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Unified sidebar configuration for ELEVATE Design System
 * Single comprehensive navigation with full hierarchy
 * All sections accessible from one unified sidebar
 * 
 * Benefits:
 * - Complete navigation hierarchy in sidebar
 * - No need to switch between different sections
 * - Auto-generated content within each category
 * - Collapsible sections for better organization
 */
const sidebars: SidebarsConfig = {
  // Main unified sidebar - accordion style (only one section expanded)
  mainSidebar: [
    {
      type: 'category',
      label: 'Home',
      link: {
        type: 'doc',
        id: 'home/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'home',
        },
      ],
      collapsed: false,
      className: 'sidebar-accordion-section',
      customProps: {
        accordion: true,
      },
    },
    {
      type: 'category',
      label: 'Design',
      link: {
        type: 'doc',
        id: 'design/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'design',
        },
      ],
      collapsed: true,
      className: 'sidebar-accordion-section',
      customProps: {
        accordion: true,
      },
    },
    {
      type: 'category',
      label: 'Guidelines',
      link: {
        type: 'doc',
        id: 'guidelines/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guidelines',
        },
      ],
      collapsed: true,
      className: 'sidebar-accordion-section',
      customProps: {
        accordion: true,
      },
    },
    {
      type: 'category',
      label: 'Components',
      link: {
        type: 'doc',
        id: 'components/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'components',
        },
      ],
      collapsed: true,
      className: 'sidebar-accordion-section',
      customProps: {
        accordion: true,
      },
    },
    {
      type: 'category',
      label: 'Patterns',
      link: {
        type: 'doc',
        id: 'patterns/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'patterns',
        },
      ],
      collapsed: true,
      className: 'sidebar-accordion-section',
      customProps: {
        accordion: true,
      },
    },
    {
      type: 'category',
      label: 'DS Components',
      link: {
        type: 'doc',
        id: 'ds/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ds',
        },
      ],
      collapsed: true,
      className: 'sidebar-accordion-section',
      customProps: {
        accordion: true,
      },
    },
  ],
};

export default sidebars;